import type { Metadata } from "next";
import { ContextProvider } from "../providers/context-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children?: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>{children}</ContextProvider>
            </body>
        </html>
    );
}
